services:
  jhsolution-homepage-main:
    container_name: jhsolution-homepage-main
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: company_home:latest
    ports:
      - "8050:8050"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 8050
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage-main.rule=Host(`www.jh-solution.net`)"
      - "traefik.http.routers.homepage-main.tls=true" # TLS 활성화 (HTTPS 사용)
      - "traefik.http.routers.homepage-main.entrypoints=websecure" # websecure (8443) 엔트리포인트 사용
      - "traefik.http.routers.homepage-main.tls.certresolver=sslresolver" # Let's Encrypt 인증서 리졸버
      - "traefik.http.services.homepage-main.loadbalancer.server.port=8050" # 홈페이지 컨테이너의 내부 포트
networks:
  traefik-proxy:
    external: true # Traefik과 서비스들이 공유할 네트워크
